/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2818773fb62da549e7f177cdfa090296)
interface __BaseEnv_Env {
	ALLOWED_REPOSITORIES: "dinkuskit/commerce,dinkuskit/template-store,dinkuskit/inventory,dinkuskit/payments,dinkuskit/dinkuskit";
	RECORDS: DurableObjectNamespace<import("./src/index").RecordTuple>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RecordTuple";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_REPOSITORIES">> {}
}
