/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fb04787cd7980b615ee0b550c7159eb7)
interface __BaseEnv_Env {
	ALLOWED_REPOSITORIES: "dinkuskit/blocks,dinkuskit/template-store,dinkuskit/template-services,dinkuskit/template-marketing,dinkuskit/inventory,dinkuskit/coupons,dinkuskit/bundles,dinkuskit/clawsweeper,dinkuskit/clawsweeper-state,dinkuskit/commerce,dinkuskit/payments,dinkuskit/ship,dinkuskit/dinkuskit";
	RECORDS: DurableObjectNamespace<import("./src/index").RecordTuple>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RecordTuple";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_REPOSITORIES">> {}
}
